spring:
  application:
    name: tcc
  datasource:
    url: jdbc:postgresql://localhost:5432/tccdbo

    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  jackson:
    time-format: HH:mm
    serialization:
      write-dates-as-timestamps: false
jwt:
  private:
    key: "classpath:chave_privada.key"
  public:
    key: "classpath:chave_publica.pub"
